services:
  - type: web
    name: outdoor-digital
    env: python
    region: sao
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHONFAULTHANDLER
        value: 1
    healthCheckPath: /
    healthCheckTimeout: 60
    instanceCount: 1
    instanceSize: free
    autoDeploy: true
    env:
      - key: PYTHONPATH
        value: .
    plan: free
    disk:
      name: outdoor-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
